<?php require_once("View/template/header.phtml") ?>

<div class="grid-container body_container" id="account_wrapper">
    <h1>Hello <?php echo $user->getFirstname() ?></h1>

    <div class="grid-margin-x grid-x" id="account_info">

        <div id="personal_info" class="cell large-6 small-12 account_wrappers">
            <h4>Account Info</h4>
            <h5 class="edit_acc_btn" onclick='toggleEditInfo("personal", <?php echo $encoded ?>)'>edit</h5>

            <h5><?php echo $user->getFirstname() . " " . $user->getLastname() ?></h5>
            <h5><?php echo $user->getEmail() ?></h5>
            <h5><?php echo $user->getDob() ?></h5>
        
        </div>

        <div id="address_info" class="cell large-6 small-12 account_wrappers">
            <div class="address_wrapper">
                <h4>Address Info</h4>
                <?php 
                // GO THROUGH EACH ADDRESS ARRAY
                    //ITERATE - PRINT OUT EACH LINE
                foreach($addresses as $key => $value) {
                    echo "<div class='indiv_address_wrapper'><h5 onclick='editAddress(". $key .", ". json_encode($value) .")' class='edit_acc_btn'>edit</h5>";
                    foreach($value as $k => $v) {
                    echo '<h5>'.$v.'</h5>';
                    }
                    echo '</div>';
                } 
                // $adr_counter = 0;
                // for($i)
                
                // count
                //loop through .length
                ?>
            </div>
            <div onclick='addPersonalInfo(<?php echo json_encode($address_template) ?>)' class="add_account_info">
                <i class="fas fa-plus"></i>
                <h4>Add Address</h4>
            </div>
        </div>

        <div id="payment_info" class="cell large-6 small-12 account_wrappers">
            <div class="address_wrapper">
                <h4>Payment Info</h4>
                <h5 class="edit_acc_btn">edit</h5>
                <div class="add_account_info">
                    <i class="fas fa-plus"></i>
                    <h4>Add Address</h4>
                </div>
            </div>
        </div>
    </div>
    </div>
    

</div>
<!-- 
<div class="account_form_pane cell large-5" id="personal_info_edit account_form_pane">
    <h3 class="personal_edit_header">Personal Info</h3>
    <div class="edit_input_wrapper">
        <label>Firstname</label>
        <input type="text" id="edit_firstname" name="edit_firstname">
    </div>
    <div class="edit_input_wrapper">
        <label>Lastname</label>
        <input type="text" id="edit_lastname" name="edit_lastname">
    </div>
    <div class="edit_input_wrapper">
        <label>Email</label>
        <input type="text" id="edit_email" name="edit_email">
    </div>
    <div class="edit_input_wrapper">
        <label>Password</label>
        <input type="text" id="edit_pass" name="edit_pass">
    </div>
    <div class="edit_input_wrapper">
        <label>Date of Birth</label>
        <input type="text" id="edit_Dob" name="edit_Dob">
    </div>

    <div class="edit_btn_wrapper">
        <div class="edit_btn button">Submit</div>
        <div class="edit_btn button">Reset</div>
    </div>
</div> -->

<div class="account_form_pane cell large-5" id="account_form_pane">
    <h3 class="personal_edit_header">Personal Info</h3>
    <i class="fas fa-times" id="close_edit_pane" onclick="toggleEditInfo(null,null)"></i>
    
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" id="edit_form_wrapper"></form>

    <div class="edit_btn_wrapper">
        <div class="edit_btn button">Submit</div>
        <div class="edit_btn button">Reset</div>
    </div>
</div>



