<?php require_once("template/header.phtml") ?>
<div class="grid-x body_container cell small-11" id="basket_body">
  <h1>basket</h1>
  <div class="grid-x grid-margin-x cell" id="basket_wrapper">
    <?php
    foreach($view->products as $item) {

      // $product_data = new ProductDataSet();
      // $set_product = $product_data->fetchProduct($item['id']);
          $color = explode(',', $item->getColor());

      echo '<div class="basket_item_wrapper grid-x grid-margin-x cell">

        <img class="cell small-5" placeholder="product img" src="/img/'. $item->getImg() .'" />

        <div id="basket_item_info">
          <div class="item_essential_info">
            <h2>'.  $item->getName() .'</h2>
            <h4>£'. $item->getPrice() .'</h4>
          </div>
          <div class="grid-x" id="basket_chosen_details">

            <div class="basket_item_color">
              <span>Colour: </span><span value="'. $color[0] .'">'. $color[1] .'</span>
            </div>

            <div class="basket_item_size">
              <span>size: </span><span>'. $item->getSize() .'</span>
            </div>


            <div class="basket_item_quantity">
              <div>
                <span>qty:</span>
                <select id="basket_item_select">
                  <option value="'.$item->getQuantity().'">'.$item->getQuantity().'</option>
                </select>
              </div>
            </div>

            <button class="remove_b_item button"><i class="fas fa-times"></i></button>
          </div>
        </div>

      </div>
      ';


    }
    ?>
  </div>
  <div id="basket_checkout" class="cell">
    
    <div id="basket_total">
      <?php 
      $total = 0;
      foreach ($view->products as $product) {    

        $product_total = $product->getQuantity() * $product->getPrice();

        echo '<div class=""><p>' .  $product->getName() . ' x <strong>' . $product->getQuantity() . '</strong> = </p><p>£' . $product_total . '</p></div>';
        $total = $total + $product_total;

      } 
      echo '<div id="checkout_total"><p>total: </p><p>£'. $total .'</p></div>'
      ?>
    </div>

    <div id="payment_btns_wrapper">
      <div id="card_payment_btn" class="payment_btn"><div><p>pay by </p></div><div><i class="fab fa-cc-visa"></i><i class="fab fa-cc-mastercard"></i></div></div>
      <div id="paypal_payment_btn" class="payment_btn"><div><p>pay by </p></div><div><i class="fab fa-paypal"></i></div></div>
      <div id="apple_payment_btn" class="payment_btn"><div><p>pay by </p></div><div><i class="fab fa-apple-pay"></i></div></div>
    </div>
    

    <?php// var_dump($_SESSION['basket'])?>

  </div>
</div>
