<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="/css/style.css" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.8.2/js/all.js" integrity="sha384-DJ25uNYET2XCl5ZF++U8eNxPWqcKohUUBUpKGlNLMchM7q4Wjg2CUpjHLaL8yYPH" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.4.3/dist/css/foundation.min.css" integrity="sha256-GSio8qamaXapM8Fq9JYdGNTvk/dgs+cMLgPeevOYEx0= sha384-wAweiGTn38CY2DSwAaEffed6iMeflc0FMiuptanbN4J+ib+342gKGpvYRWubPd/+ sha512-QHEb6jOC8SaGTmYmGU19u2FhIfeG+t/hSacIWPpDzOp5yygnthL3JwnilM7LM1dOAbJv62R+/FICfsrKUqv4Gg==" crossorigin="anonymous">
    <title><?php echo $view->pageTitle ?></title>
    <script src="/js/index.js" type="text/javascript"></script>
    <link rel="icon" href="/img/tee_flat.jpg" type="image/gif" sizes="16x16">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
</head>

<body role="document" class="grid-x">
  <div class="grid-x grid-margin-x align-justify " id="nav">

    <div class="vertical medium-horizontal menu grid-x" id="navbar_wrapper">

      <i class="fas fa-bars" id="nav_menu"></i>

      <ul id="nav-left" class="cell small-3">
        <li class="main_nav_btn"><a href="../index.php"><i class="fas fa-minus"></i> <span>Home</span></a></li>
        <li class="main_nav_btn" id="nav_shop_btn"><a id="nav_shop_link" href="../products.php"><i class="fas fa-minus"></i> <span>Shop</span></a>
          <ul id="nav_shop_link_list">
            <ul id="nav_collections_list">
            <?php
              require_once('Model/ProductDataSet.php');
              $ProductDS = new ProductDataSet();
              $theArr = $ProductDS->FetchAllCategories();
              
              foreach($theArr['collection'] as $collection) {
                echo '<li class="category_link"><a href="../../collection.php/?collNum='. $collection['id'] .'"><i class="fas fa-minus"></i><span>'.$collection['name'].'</span></a></li>';
              }

            ?>
            </ul>
            <ul id="garment_nav_list">
              <div class="collection_column">
              <?php
              require_once('Model/ProductDataSet.php');
              $ProductDS = new ProductDataSet();
              $theArr = $ProductDS->FetchAllCategories();
              $counter = 0;
              
              foreach($theArr['category'] as $category) {
                if($counter > 3) {
                  echo '</div><div class="collection_column"><li class="category_link"><a href="../../collection.php/?collNum='. $category['id'] .'"><i class="fas fa-minus"></i><span>'.$category['name'].'</span></a></li>';
                  $counter = 0;
                } else {
                  echo '<li class="category_link"><a href="../../collection.php/?collNum='. $category['id'] .'"><i class="fas fa-minus"></i><span>'.$category['name'].'</span></a></li>';
                  $counter++;
                }
                

              }
              echo '</div>'
            ?>
            </ul>

          </ul>
        </li>

        <li class="main_nav_btn"><a href="#0" id="nav_about"><i class="fas fa-minus"></i> <span>About</span></a></li>


      </ul>


<!--     SEARCH BAR      -->

    <div class="searchbar cell auto" id="searchbar">
      <div class="searchbar_btn" id="open_search">
        <i class="fas fa-search searchbar_icon" id="open_search_btn" onclick="toggleSuggestWrapper()"></i>
      </div>

      <input required type="search" id="nav_search" placeholder="Search.." onkeyup="showSuggest(this.value)"/>

      <div class="searchbar_btn" id="search_product">
        <i class="fas fa-check searchbar_icon" id="search_btn"></i>
      </div>
    </div>


    <ul class="cell small-5 large-3" id="nav-right">
       <?php
        if(isset($_SESSION['lastname'])) : ?>
          <li id="active_login" class="logged_in main_nav_btn"><div id="logged_in_status"></div></li>
          <li id="account_btn" class="main_nav_btn"><i class="fi-list"></i> <span><?php echo $_SESSION['lastname'] ?></span></li>
        <?php else : ?>
          <li id="active_login" class="logged_out main_nav_btn"><div id="logged_in_status"></div></li>
          <li id="account_btn" class="main_nav_btn"><i class="fi-list"></i> <span>Account</span></li>
      <?php endif; ?>
      
      <li id="basket_btn" class="main_nav_btn"><i class="fi-list"></i> <span>Basket</span></li>
    </ul>

  </div>


<!-- LOGIN -->

    <div id="account_menu" class="cell large-3 small-10 entry_no_show">

      <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" id="nav_entry" class="callout text-center">
        <?php if(isset($_SESSION['lastname'])) : ?>
          <input class="button expanded" type="submit" value="Log out" name="log_out_user">

        <?php else : ?>
        <h2>Log in to Account</h2>
        <div class="floated-label-wrapper">
          <label for="email">Email</label>
          <input type="email" class="login_input" id="login_email" name="email" placeholder="Email" required>
        </div>

        <div class="floated-label-wrapper">
          <label for="pass">Password</label>
          <input type="password" class="login_input" required id="login_pass" name="password" placeholder="Password">
        </div>

        <div id="login_error_box">
          <p id="login_error"></p>
        </div>

          <div id="login_btn" class="button expanded" onclick="logInUser(this);" name="log_in">Log in</div>
      <?php endif; ?>
      </form>
    </div>

<!--  SUGGESTION / SEARCH WRAPPER -->
    <div id="suggest_bar_wrapper">
      <p id="search_suggest">suggestions :</p>
      <div>

        <div id="suggest_wrapper">
          
        </div>
      </div>

    </div>

    </div>

    <!-- FOREACH ITEM IN SESSION(BASKET) -->
      <?php //var_dump($_SESSION['basket']) ?>

    <div class="cell large-3 small-10" id="basket">

      <?php
      if(isset($_SESSION['basket'])) {

        $i = 0;

        foreach ($_SESSION['basket'] as $item) {
          $i++;

          require_once('Model/ProductDataSet.php');
          require_once('Model/ProductData.php'); 
          $aProductDataSet = new ProductDataSet();

          $basketItem = $aProductDataSet->FetchProduct($item[id]);

          // var_dump($this_item);

          $this_item = $basketItem;

          // echo count($this_item);
          //create function for this?? DRY CODE + add to basket.php
          echo '<div class="basket_item" value="'. $i .'">
            <img src="/img/'. $this_item->getProductImg() .'"/>

            <div class="bitem_info">

            <div class="bitem_name">
              <h4 class="item_name">'. $this_item->getProductName() .'</h4>
            </div>

            <div class="bitem_selected">
              <h6 class="item_size">size : '. $item[size] .'</h6>
              <h6 class="item_color">color : '. $item[color] .'</h6>
            </div>

          </div>
          </div>';

        }
      }
      ?>
      <div class="button" id="basket_to_payment_btn"><a href="../basket.php">go to basket</a></div>


    </div>
  </div>

  <?php
    // $time = $_SERVER['REQUEST_TIME'];

    // // 15 MIN TIMEOUT
    // $timeout_duration = 9;

    // if (isset($_SESSION['LAST_ACTIVITY']) && 
    //   ($time - $_SESSION['LAST_ACTIVITY']) > $timeout_duration) {
    //     session_unset();
    //     session_destroy();
    //     session_start();
    // }
    // $_SESSION['LAST_ACTIVITY'] = $time;
  ?>


