<?php
require_once("template/header.phtml");
?>

<?php echo $user ?>

<!-- <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="callout text-center">

  <h2>Log in to Account</h2>
  <div class="floated-label-wrapper">
    <label for="full-name">Full name</label>
    <input type="text" id="full-name" name="name" placeholder="Full name">
  </div>
  <div class="floated-label-wrapper">
    <label for="email">Email</label>
    <input type="email" id="email" name="email" placeholder="Email">
  </div>
  <div class="floated-label-wrapper">
    <label for="pass">Password</label>
    <input type="password" id="pass" name="password" placeholder="Password">
  </div>
  <input class="button expanded" type="submit" value="Log in" name="log_in"  onclick="logInUser(); return false" >
  <input class="button expanded" type="submit" value="Log out" name="log_out_user">
</form> -->
